name: Your New Jekyll Site
markdown: redcarpet
pygments: true
prose:
  rooturl: '_posts'
  ignore:
    - .gitignore
    - _config.yml
    - Gemfile
    - Gemfile.lock
    - index.html
    - /_layouts
    - /_plugins
    - /_includes
    - /contact
    - /css
