name: Your New Jekyll Site
markdown: redcarpet
pygments: true
prose:
  ignore:
    - .gitignore
    - _config.yml
    - Gemfile
    - Gemfile.lock
    - index.html
    - /_layouts
    - /_plugins
    - /contact
    - /css
